### ISSUE TITLE
'msg' is not recognized as an internal or external program

### ISSUE THREAD

**Issue by rfahmi** [restuwahyu13/bangjago-android-emulator#1]
Saat install new AVD
Environtment windows 10 x64

**Comment by restuwahyu13** [comment]
untuk mengatasi issue terkait **msg' is not recognized as an internal or external program**, silahkan ikuti step by step berikut ini.

+ uninstall android studio menggunakan iobit uninstaller, setelah selesai restart pc/laptop
+ pastikan folder android studio sudah terhapus baik di **C:\Program Files\Android** atau di **C:\Users\Test\AppData\Local\Android**
+ kemudian install android studio last version dan install haxm melalui AS ( untuk saat ini masih manual  )
+ download bangjago emulator yang melalui **bitfly** dan follow step by step tutorial yang tersedia baik melalui github atau youtube
+ jangan lupa tambahkan **ANDROID_HOME** dan **JAVA_HOME** ke **environment** dari masing - masing path
